# Generated by Django 5.2.17 on 2026-09-21 13:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione sintetica del debito')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message="L'importo del debito deve essere maggiore di zero.")], verbose_name='Importo debito (€)')),
                ('stato', models.CharField(choices=[('nuova', 'Nuova'), ('in_lavorazione', 'In lavorazione'), ('chiusa', 'Chiusa')], default='nuova', max_length=20, verbose_name='Stato pratica')),
                ('creata_il', models.DateTimeField(auto_now_add=True, verbose_name='Data e ora apertura')),
                ('aggiornata_il', models.DateTimeField(auto_now=True, verbose_name='Data e ora ultimo aggiornamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pratiche', to='customers.customer', verbose_name='Cliente intestatario')),
            ],
            options={
                'verbose_name': 'Pratica',
                'verbose_name_plural': 'Pratiche',
                'ordering': ['-creata_il'],
            },
        ),
    ]
