# Generated by Django 5.2.17 on 2026-09-21 13:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_email_and_more'),
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pratica',
            constraint=models.CheckConstraint(condition=models.Q(('importo__gt', Decimal('0.00'))), name='pratica_importo_positivo'),
        ),
    ]
